name: Test

on: [push, pull_request]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Rudder Transformer Test and Publish
        uses: ./
        with:
          metaPath: './code/meta.json'
          email: 'sayan+10@rudderlabs.com'
          accessKey: ${{ secrets.ACCESS_KEY }}
          serverEndpoint: 'https://1a3bd53e8df2.ngrok.io'
          uploadTestArtifact: true